/* eslint-disable @next/next/no-html-link-for-pages */
import { Photo, Arrow } from './components';
import { bookingUrl } from './site';
import ActivityPicker from './activity-picker';

export function BrandHeader({ activity }: { activity?: string }) {
  return <><a className="skip-link" href="#main">Skip to content</a><header className="bm-header" id="top"><a className="bm-wordmark" href="/" aria-label="Bali Monster home">BALI MONSTER<span>{activity || 'OCEAN ADVENTURES'}</span></a><nav aria-label="Main navigation"><a href="/charters">Boat charters</a><a href="/spearfishing">Spearfishing</a><a className="bm-nav-cta" href={bookingUrl(activity || 'a trip in Bali')}>Plan a trip <Arrow /></a></nav></header></>;
}
export function BrandFooter() {
  return <footer className="bm-footer"><a className="bm-wordmark" href="/">BALI MONSTER<span>BALI, INDONESIA</span></a><p>A little further from the everyday.</p><a href="/">Choose another adventure ↗</a><small>© {new Date().getFullYear()} Bali Monster</small></footer>;
}
const activities = [
  {id:'snorkeling',title:'Snorkeling',subtitle:'A different world, just below.',detail:'Spend time at the surface and take in the blue. Tell us your swimming experience so we can discuss a suitable trip.',symbol:'≈'},
  {id:'sunsets',title:'Sunsets',subtitle:'Stay out for the last light.',detail:'Trade the shore for an evening on the water. Ask us about timing and options for your group.',symbol:'☼'},
  {id:'camping',title:'Camping',subtitle:'Let the day become a getaway.',detail:'Have an overnight adventure in mind? Talk to us about locations, arrangements, and what to bring.',symbol:'△'},
  {id:'sportfishing',title:'Sportfishing',subtitle:'A rod. A reel. Open water.',detail:'Plan a fishing day from the boat. Discuss your experience, equipment, and the kind of trip you have in mind.',symbol:'⌁'},
  {id:'island-transfer',title:'Island transfer',subtitle:'Make the journey part of it.',detail:'Share your departure point, destination, dates, and group size. We will discuss routes and availability.',symbol:'↗'},
];
export function ActivityCards({ detail = false }: { detail?: boolean }) {
  return <div className={`bm-activities${detail ? ' bm-activity-details' : ''}`}>{activities.map((a,i)=><article key={a.id} id={detail ? a.id : undefined}><div className="bm-activity-top"><span>0{i+1}</span><span aria-hidden="true">{a.symbol}</span></div><h3>{a.title}</h3><p>{detail ? a.detail : a.subtitle}</p><a href={detail ? bookingUrl(a.title.toLowerCase()) : `/charters#${a.id}`}>{detail ? `Ask about ${a.title.toLowerCase()}` : 'Explore trip'} <Arrow /></a></article>)}</div>;
}
function ChoiceCards() {
  return <div className="bm-choices" id="experiences"><a className="bm-choice" href="/charters"><Photo id="coastal-run" /><div><p className="bm-kicker">01 / ABOVE &amp; AROUND</p><h2>Boat charters <Arrow /></h2><p>Snorkeling. Sunsets. Camping.<br />Sportfishing. Island transfers.</p><span className="bm-link">Find your boat day →</span></div></a><a className="bm-choice" href="/spearfishing"><Photo id="below-the-surface" /><div><p className="bm-kicker">02 / BELOW &amp; BEYOND</p><h2>Spearfishing <Arrow /></h2><p>Get below the surface.<br />Find your kind of adventure.</p><span className="bm-link">Explore the deep blue →</span></div></a></div>;
}
export function Landing({ variant }: { variant: 'popup' | 'split' | 'activity' }) {
 return <div className={`bm bm-${variant}`}><BrandHeader /><main id="main">
  {variant === 'split' ? <><section className="bm-split-intro"><p className="bm-kicker">BALI, INDONESIA / A DIFFERENT KIND OF DAY</p><h1>ONE OCEAN.<br /><span>YOUR ADVENTURE.</span></h1><p>Welcome to Bali Monster. Where do you want to go?</p></section><ChoiceCards /></> :
  <section className="bm-hero"><Photo id="coastal-run" priority sizes="(max-width: 600px) 1200px, 100vw" /><div className="bm-hero-shade" /><div className="bm-hero-copy"><p className="bm-kicker">BALI, INDONESIA · OUT OF THE EVERYDAY</p><h1>{variant === 'activity' ? <>A LITTLE MORE<br /><em>ocean.</em></> : <>THE OCEAN.<br />YOUR WAY.</>}</h1><p>Hidden coastlines. Saltwater days. A slower way home.<br />Find your Bali with Bali Monster.</p><div className="bm-hero-actions">{variant === 'popup' ? <ActivityPicker /> : <><a className="bm-button" href="/charters">Find your boat day <Arrow /></a><a className="bm-quiet-link" href="/spearfishing">Here for spearfishing? ↗</a></>}</div></div><div className="bm-hero-bottom"><span>GOOD DAYS START ON THE WATER.</span><a href="#experiences">Explore ↓</a></div></section>}
  <div className="bm-ticker"><span>BALI MONSTER</span><span>SNORKELING</span><span>SUNSETS</span><span>ISLAND DAYS</span><span>OPEN WATER</span></div>
  {variant === 'popup' && <section className="bm-section"><div className="bm-section-heading"><p className="bm-kicker">FIND YOUR WAY OUT THERE</p><h2>Two ways in.<br />A world to explore.</h2></div><ChoiceCards /></section>}
  <section className="bm-section" id={variant === 'activity' ? 'experiences' : 'boat-days'}><div className="bm-section-heading"><div><p className="bm-kicker">BALI MONSTER / BOAT CHARTERS</p><h2>No two days<br />need look alike.</h2></div><p>Float above the blue. Follow the coast.<br />Catch the last of the light.<br />Pick the day that feels like you.</p></div><ActivityCards /></section>
  <section className="bm-story"><Photo id="at-the-surface" /><div><p className="bm-kicker">LESS SCHEDULE. MORE SALTWATER.</p><h2>Make room<br />for a boat day.</h2><p>Start with what you love. Tell us your dates, your group, and what you have in mind. We’ll talk through the details together.</p><a className="bm-button" href={bookingUrl('a boat charter')}>Let’s plan your day <Arrow /></a></div></section>
  <section className="bm-end"><p className="bm-kicker">BALI MONSTER / SPEARFISHING</p><h2>Drawn to the deep?</h2><p>Discover the spearfishing side of Bali Monster.</p><a className="bm-link" href="/spearfishing">Explore spearfishing <Arrow /></a></section>
 </main><BrandFooter /></div>;
}
export function Charters() {
 return <div className="bm bm-charters"><BrandHeader activity="BOAT CHARTERS" /><main id="main"><section className="bm-hero"><Photo id="coastal-run" priority sizes="(max-width: 600px) 1200px, 100vw" /><div className="bm-hero-shade" /><div className="bm-hero-copy"><p className="bm-kicker">BALI MONSTER / BOAT CHARTERS</p><h1>YOUR DAY.<br /><em>wide open.</em></h1><p>Snorkel the blue. Chase the sunset. Go a little further.<br />A boat day built around what you love.</p><a className="bm-button" href="#experiences">Find your kind of day <Arrow /></a></div></section><section className="bm-section" id="experiences"><div className="bm-section-heading"><div><p className="bm-kicker">FIVE WAYS TO GET OUT THERE</p><h2>Where shall<br />we take you?</h2></div><p>Start with an idea. We’ll discuss routes,<br />conditions, pricing, and availability<br />before you book.</p></div><ActivityCards detail /></section><section className="bm-story"><Photo id="at-the-surface" /><div><p className="bm-kicker">BALI MONSTER / SNORKELING</p><h2>Take a look<br />below.</h2><p>A day on the water can be about simply being there. Tell us your swimming experience and who’s coming along. We’ll help you explore the options.</p><a className="bm-button" href={bookingUrl('snorkeling')}>Plan a snorkeling trip <Arrow /></a></div></section><section className="bm-end"><p className="bm-kicker">GOOD TRIPS START WITH A CONVERSATION</p><h2>Let’s make a day of it.</h2><p>Share your dates, group size, and activity.<br />Confirm equipment, meeting points, and inclusions with the team.</p><a className="bm-button" href={bookingUrl('a boat charter')}>Chat on WhatsApp <Arrow /></a></section></main><BrandFooter /></div>;
}
